### PR TITLE
make dx_config accept a string to build dxtools.conf related to issue #136

### PR DESCRIPTION
**Pull request by rncintra**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Build was run locally and any changes were pushed
- [ ] Lint has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

We needed the capability to accept a string to build dxconf through dxconfig. This is related to # 136
Issue Number: 136

## What is the new behavior?

- The command dxconfig now accepts strings are parameters while generating dxtolls.conf. Example: dxconfig -convert todxconf -text delphixhml.csfcpv.wcorp.carrefour.com,10.113.98.190,devops,devops,80,true,false -configfile dxtools.conf
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by DSTOLF** [comment]
This PR is about feature request #136 

Customer has tested locally by executing the perl script directly.

**Comment by rncintra** [comment]
@DSTOLF @pioro I had to fix a duplicated if on my code. I didn't noticed while commiting the changes eariler today. all good now. Thanks!

**Comment by rncintra** [comment]
Guys,
We have built this locally and are now using succesfully within our containers to communicate with Delphix.

**Comment by pioro** [comment]
Thank you for your contribution. I will merge this PR into the next release

**Pull request merged**
