### PR TITLE
lib/DB2VDB_obj.pm, lib/Databases.pm, bin/dx_provision_vdb.pl, Dockerf…

### LINKED ISSUE #64: How to contribute changes
Hi,

I have added a new `DB2VDB_obj` class and changed dx_provision_vdb to accept a new `db2` type for clone provisioning (adding a new dSource is TBD).

I'd like to submit a PR to this repo, what are the guidelines for contributing?

Best regards.

### PR DESCRIPTION
**Pull request by DSTOLF**
closes #64
lib/DB2VDB_obj.pm , lib/Databases.pm - New DB2 Database object derived from vFiles
bin/dx_provision_vdb.pl -  changes to dx_provision_database for new DB type
Dockerfile - multi-stage Dockerfile to build an image with all the binaries

### CODE REVIEW

**Comment by pioro** [comment]
Hi,

I'm working on merge now. Thanks for all your work !

regards,
Marcin

**Comment by DSTOLF** [comment]
Thanks @pioro 

Please let me know if there's anything I should change, I'm not super well versed in Perl.

Also, as soon as these changes are official, I think I'll write something about integrating dxtoolkit with Gitlab CI/CD dynamic environments (hence, the Dockerfile I suggested).

Regards!

**Comment by pioro** [comment]
merged with development branch
Now I will add support for adding dSource and dx_get_db_env to display database types not vFiles

**Comment by pioro** [comment]
Thanks again @DSTOLF for this initial work.
I'm not a Perl expert either but you keep same style like me so all looks good

**Comment by DSTOLF** [comment]
@pioro great news!

Ping me if you need anything

**Pull request closed without merging**
